const Movie = require("./models/Movie");

const MOVIES = [
  {
    title: "Dune: Part Two",
    genre: ["Sci-Fi", "Adventure", "Drama"],
    description: "Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.",
    duration: 166,
    rating: 8.8,
    poster: "https://image.tmdb.org/t/p/w500/8b8R8l88Qje9dn9OE8PY05Nxl1X.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg",
    year: 2024,
    director: "Denis Villeneuve",
    cast: ["Timothée Chalamet", "Zendaya", "Rebecca Ferguson"],
    language: "English",
    showtimes: [
      { date: "2025-04-20", time: "10:00 AM", hall: "Hall A", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-20", time: "2:00 PM",  hall: "Hall B", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-20", time: "7:00 PM",  hall: "Hall A", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-21", time: "11:00 AM", hall: "Hall C", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-21", time: "4:00 PM",  hall: "Hall B", totalSeats: 60, bookedSeats: [] },
    ],
  },
  {
    title: "Oppenheimer",
    genre: ["Drama", "History", "Thriller"],
    description: "The story of J. Robert Oppenheimer's role in the development of the atomic bomb during World War II.",
    duration: 180,
    rating: 9.0,
    poster: "https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/fm6KqXpk3M2HVveHwCrBSSBaO0V.jpg",
    year: 2023,
    director: "Christopher Nolan",
    cast: ["Cillian Murphy", "Emily Blunt", "Matt Damon"],
    language: "English",
    showtimes: [
      { date: "2025-04-20", time: "11:00 AM", hall: "Hall B", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-20", time: "3:00 PM",  hall: "Hall C", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-20", time: "8:00 PM",  hall: "Hall A", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-21", time: "1:00 PM",  hall: "Hall A", totalSeats: 60, bookedSeats: [] },
    ],
  },
  {
    title: "Deadpool & Wolverine",
    genre: ["Action", "Comedy", "Superhero"],
    description: "Deadpool is recruited by the Time Variance Authority and allies with Wolverine to protect his world.",
    duration: 127,
    rating: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg",
    year: 2024,
    director: "Shawn Levy",
    cast: ["Ryan Reynolds", "Hugh Jackman", "Emma Corrin"],
    language: "English",
    showtimes: [
      { date: "2025-04-20", time: "12:00 PM", hall: "Hall C", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-20", time: "5:00 PM",  hall: "Hall A", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-20", time: "9:00 PM",  hall: "Hall B", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-21", time: "2:00 PM",  hall: "Hall C", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-21", time: "6:00 PM",  hall: "Hall A", totalSeats: 60, bookedSeats: [] },
    ],
  },
  {
    title: "Inside Out 2",
    genre: ["Animation", "Comedy", "Family"],
    description: "A new emotion — Anxiety — joins the crew inside Riley's mind as she faces the challenges of adolescence.",
    duration: 100,
    rating: 7.9,
    poster: "https://image.tmdb.org/t/p/w500/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/xg27NrXi7VXCGUr7MG75UqLl6Vg.jpg",
    year: 2024,
    director: "Kelsey Mann",
    cast: ["Amy Poehler", "Maya Hawke", "Liza Lapira"],
    language: "English",
    showtimes: [
      { date: "2025-04-20", time: "10:30 AM", hall: "Hall C", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-20", time: "1:00 PM",  hall: "Hall A", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-20", time: "4:30 PM",  hall: "Hall B", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-21", time: "10:00 AM", hall: "Hall A", totalSeats: 60, bookedSeats: [] },
    ],
  },
  {
    title: "The Batman",
    genre: ["Action", "Crime", "Drama"],
    description: "In his second year of fighting crime, Batman uncovers corruption in Gotham City that connects to his own family.",
    duration: 176,
    rating: 8.3,
    poster: "https://image.tmdb.org/t/p/w500/74xTEgt7R36Fpooo50r9T25onhq.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/b0PlSFdDwbyK0cf5RxwDpaOJQvQ.jpg",
    year: 2022,
    director: "Matt Reeves",
    cast: ["Robert Pattinson", "Zoë Kravitz", "Paul Dano"],
    language: "English",
    showtimes: [
      { date: "2025-04-20", time: "6:00 PM",  hall: "Hall C", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-21", time: "3:00 PM",  hall: "Hall B", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-21", time: "8:00 PM",  hall: "Hall A", totalSeats: 60, bookedSeats: [] },
    ],
  },
  {
    title: "Interstellar",
    genre: ["Sci-Fi", "Drama", "Adventure"],
    description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    duration: 169,
    rating: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/pbrkL804WsngHpbeadCMi1TXoOF.jpg",
    year: 2014,
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"],
    language: "English",
    showtimes: [
      { date: "2025-04-20", time: "5:30 PM",  hall: "Hall B", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-21", time: "12:00 PM", hall: "Hall C", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-21", time: "7:30 PM",  hall: "Hall B", totalSeats: 60, bookedSeats: [] },
    ],
  },
  {
    title: "Avatar: The Way of Water",
    genre: ["Sci-Fi", "Action", "Adventure"],
    description: "Jake Sully and Neytiri form a family and face new threats as they protect their home on Pandora.",
    duration: 192,
    rating: 7.8,
    poster: "https://image.tmdb.org/t/p/w500/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/s16H6tpK2utvwpaZCB2npfpTEIT.jpg",
    year: 2022,
    director: "James Cameron",
    cast: ["Sam Worthington", "Zoe Saldaña", "Sigourney Weaver"],
    language: "English",
    showtimes: [
      { date: "2025-04-20", time: "9:00 AM",  hall: "Hall A", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-20", time: "3:30 PM",  hall: "Hall B", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-21", time: "5:00 PM",  hall: "Hall C", totalSeats: 60, bookedSeats: [] },
    ],
  },
  {
    title: "Joker",
    genre: ["Drama", "Crime", "Thriller"],
    description: "A failed comedian descends into madness and becomes the iconic Batman villain, the Joker.",
    duration: 122,
    rating: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    backdrop: "https://image.tmdb.org/t/p/w1280/n6bUvigpRFqSwmPp1m2YADdbRBc.jpg",
    year: 2019,
    director: "Todd Phillips",
    cast: ["Joaquin Phoenix", "Robert De Niro", "Zazie Beetz"],
    language: "English",
    showtimes: [
      { date: "2025-04-20", time: "2:30 PM",  hall: "Hall A", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-20", time: "6:30 PM",  hall: "Hall C", totalSeats: 60, bookedSeats: [] },
      { date: "2025-04-21", time: "9:00 PM",  hall: "Hall B", totalSeats: 60, bookedSeats: [] },
    ],
  },
];

async function seedMovies() {
  const count = await Movie.countDocuments();
  if (count === 0) {
    await Movie.insertMany(MOVIES);
    console.log("✅ 8 movies seeded successfully");
  }
}

module.exports = { seedMovies };
